CREATE TABLE aca_mab_customers (Aca_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
ACA_Name CHAR(50) NOT NULL,
ACA_Bname CHAR(50) NOT NULL,
);
CREATE TABLE aca_mab_users (User_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
C_Fname CHAR(50) NOT NULL,
C_Lname CHAR(50) NOT NULL,
FOREIGN KEY (Aca_ID) REFERENCES aca_mab_customers (Aca_ID)
);
CREATE TABLE aca_mab (Mac_ID BIGINT UNSIGNED NOT NULL PRIMARY KEY,
FOREIGN KEY (Aca_ID) REFERENCES aca_mab_customers (Aca_ID)
);
CREATE TABLE aca_mab_admin (Admin_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
A_Fname CHAR(50) NOT NULL,
A_Lname CHAR(50) NOT NULL,
FOREIGN KEY (Aca_ID) REFERENCES aca_mab_customers (Aca_ID)
);
CREATE TABLE aca_mab_metadata (
Mac_ID BIGINT UNSIGNED NOT NUL,
First_Seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
Last_Seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
Status CHAR (2),
Count INT UNSIGNED,
PRIMARY KEY (Mac_ID),
FOREIGN KEY (Mac_ID) REFERENCES aca_mab (Mac_ID)
);
CREATE TABLE aca_mab_dates (Date_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
Mac_ID BIGINT UNSIGNED NOT NUL,
Last_Seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (Mac_ID) REFERENCES aca_mab (Mac_ID),
FOREIGN KEY (Last_Seen) REFERENCES aca_mab_metadata (Mac_ID)
);
CREATE TABLE aca_mab_notes (Note_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
Mac_ID BIGINT UNSIGNED NOT NUL,
Note VARCHAR (1000) NOT NULL,
Last_Seen TIMESTAMP NOT NULL AUTO_INCREMENT,
Status CHAR (2) NOT NULL,
Count INT UNSIGNED,
FOREIGN KEY (Mac_ID) REFERENCES aca_mab (Mac_ID),
FOREIGN KEY (Last_Seen) REFERENCES aca_mab_metadata (Mac_ID)
);

