<p><h4>Assignment for Gihub for 100 points</h4><hr/>
	<ol>
		<li>Create one github account</li>
		<li>Create one repo with a basic setup</li>
		<li>Go to here - https://github.com/devskilldevops/simple-php-website and clone this repo.</li>
		<li>Create any feature branch and do some changes (add something)in index.php file and commit and create PR.</br>and post that link privately to me</li>
	</ol>
</p>